select * from Tea_Shops
select * from Menu_Items
select * from Sales
select * from Ratings


-- QUESTIONS
-- 1) Lists all tea shop details ?
SELECT 
    *
FROM
    Tea_Shops


-- 2) Find Menu Items Available in the Shop ?
SELECT 
    *
FROM
    Menu_Items
WHERE
    available = 1


-- 3) Find the Total Number of Orders for Each Menu Item ?
SELECT 
    m.item_name, COUNT(s.sale_id) AS total_orders
FROM
    Sales s
        JOIN
    Menu_Items m ON s.item_id = m.item_id
GROUP BY m.item_name


-- 4) Find the Total Revenue Generated by Each Shop in different Locations ?

SELECT 
    t.country, SUM(s.quantity * m.price) AS revenue
FROM
    Menu_Items m
        JOIN
    Sales s ON m.item_id = s.item_id
        JOIN
    Tea_Shops t ON t.shop_id = s.shop_id
GROUP BY t.country


-- 5) Find the Best-Selling Item ?

SELECT 
    m.item_name, 
    SUM(s.quantity) AS total_sold
FROM 
    Sales s
JOIN 
    Menu_Items m ON s.item_id = m.item_id
GROUP BY 
    m.item_name
ORDER BY 
    total_sold DESC
LIMIT 1;


-- 6) Count the Total Number of Ratings for Each Shop ?
SELECT 
    s.shop_name, COUNT(r.rating) AS total_rating
FROM
    Tea_Shops s
        JOIN
    Ratings r ON s.shop_id = r.shop_id
GROUP BY s.shop_name

-- 7) List All Shops with an Average Rating Above 4.5 ?

SELECT 
    s.shop_name, 
    AVG(r.rating) AS average_rating
FROM 
    Tea_Shops s
JOIN 
    Ratings r ON s.shop_id = r.shop_id
GROUP BY 
    s.shop_name
HAVING 
    AVG(r.rating) > 4.5;


-- 8) Find reviews where customers used the word "amazing" for a shop in Bangalore ?
SELECT 
    r.review, s.city
FROM
    Tea_Shops s
        JOIN
    Ratings r ON s.shop_id = r.shop_id
WHERE
    r.review LIKE '%amazing%' 
        AND s.city = 'Bangalore'


-- 9) Find the names of customers who had Masala Chai and identify the tea shop where they consumed it ?

SELECT 
    r.customer_name,
    m.item_name,
    t.shop_name
FROM 
    Sales s
JOIN 
    Menu_Items m ON s.item_id = m.item_id
JOIN 
    Tea_Shops t ON s.shop_id = t.shop_id
JOIN 
    Ratings r ON r.shop_id = t.shop_id
WHERE 
    m.item_name = 'Masala Chai';


-- 10) Find the day with the most sales ?
SELECT 
    transaction_date, SUM(quantity) AS total_sales
FROM
    sales
GROUP BY transaction_date
ORDER BY total_sales DESC
LIMIT 1